spring:
  profile: local

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:split_expenses_app
    username: sa
    password: <>
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect